/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ancud.shorturl.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ShortUrl service. Represents a row in the &quot;shorturl_ShortUrl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ancud.shorturl.model.impl.ShortUrlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ancud.shorturl.model.impl.ShortUrlImpl}.
 * </p>
 *
 * @author David
 * @see ShortUrl
 * @see de.ancud.shorturl.model.impl.ShortUrlImpl
 * @see de.ancud.shorturl.model.impl.ShortUrlModelImpl
 * @generated
 */
public interface ShortUrlModel extends BaseModel<ShortUrl> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a short url model instance should use the {@link ShortUrl} interface instead.
	 */

	/**
	 * Returns the primary key of this short url.
	 *
	 * @return the primary key of this short url
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this short url.
	 *
	 * @param primaryKey the primary key of this short url
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the short url ID of this short url.
	 *
	 * @return the short url ID of this short url
	 */
	public long getShortUrlId();

	/**
	 * Sets the short url ID of this short url.
	 *
	 * @param shortUrlId the short url ID of this short url
	 */
	public void setShortUrlId(long shortUrlId);

	/**
	 * Returns the identifier of this short url.
	 *
	 * @return the identifier of this short url
	 */
	@AutoEscape
	public String getIdentifier();

	/**
	 * Sets the identifier of this short url.
	 *
	 * @param identifier the identifier of this short url
	 */
	public void setIdentifier(String identifier);

	/**
	 * Returns the original url of this short url.
	 *
	 * @return the original url of this short url
	 */
	@AutoEscape
	public String getOriginalUrl();

	/**
	 * Sets the original url of this short url.
	 *
	 * @param originalUrl the original url of this short url
	 */
	public void setOriginalUrl(String originalUrl);

	/**
	 * Returns the company ID of this short url.
	 *
	 * @return the company ID of this short url
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this short url.
	 *
	 * @param companyId the company ID of this short url
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this short url.
	 *
	 * @return the group ID of this short url
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this short url.
	 *
	 * @param groupId the group ID of this short url
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this short url.
	 *
	 * @return the user ID of this short url
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this short url.
	 *
	 * @param userId the user ID of this short url
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this short url.
	 *
	 * @return the user uuid of this short url
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this short url.
	 *
	 * @param userUuid the user uuid of this short url
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this short url.
	 *
	 * @return the create date of this short url
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this short url.
	 *
	 * @param createDate the create date of this short url
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this short url.
	 *
	 * @return the modified date of this short url
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this short url.
	 *
	 * @param modifiedDate the modified date of this short url
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ShortUrl shortUrl);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ShortUrl> toCacheModel();

	@Override
	public ShortUrl toEscapedModel();

	@Override
	public ShortUrl toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}